jobs:
  - job: tests
    trigger: pull_request
    # Suffix for job name
    identifier: "upgrade"
    targets:
      # This target is not used at all by our tests, but it has to be one of the available - https://packit.dev/docs/configuration/#aliases
      - fedora-38-x86_64
      - fedora-38-aarch64
    # We don't need to build any packages for Fedora/RHEL/CentOS, it is not related to Strimzi tests
    skip_build: true
    tf_extra_params:
      test:
        fmf:
          name: upgrade
      settings:
        pipeline:
          timeout: 5h
  ###############################################################################################

  - job: tests
    trigger: pull_request
    # Suffix for job name
    identifier: "regression-operators"
    targets:
      # This target is not used at all by our tests, but it has to be one of the available - https://packit.dev/docs/configuration/#aliases
      - fedora-38-x86_64
      - fedora-38-aarch64
    # We don't need to build any packages for Fedora/RHEL/CentOS, it is not related to Strimzi tests
    skip_build: true
    tf_extra_params:
      test:
        fmf:
          name: regression-operators
      settings:
        pipeline:
          timeout: 10h
  ###############################################################################################

  - job: tests
    trigger: pull_request
    # Suffix for job name
    identifier: "regression-components"
    targets:
      # This target is not used at all by our tests, but it has to be one of the available - https://packit.dev/docs/configuration/#aliases
      - fedora-38-x86_64
      - fedora-38-aarch64
    # We don't need to build any packages for Fedora/RHEL/CentOS, it is not related to Strimzi tests
    skip_build: true
    tf_extra_params:
      test:
        fmf:
          name: regression-components
      settings:
        pipeline:
          timeout: 8h
  ###############################################################################################

  - job: tests
    trigger: pull_request
    # Suffix for job name
    identifier: "kraft-operators"
    targets:
      # This target is not used at all by our tests, but it has to be one of the available - https://packit.dev/docs/configuration/#aliases
      - fedora-38-x86_64
      - fedora-38-aarch64
    # We don't need to build any packages for Fedora/RHEL/CentOS, it is not related to Strimzi tests
    skip_build: true
    tf_extra_params:
      test:
        fmf:
          name: kraft-operators
      settings:
        pipeline:
          timeout: 8h
  ###############################################################################################

  - job: tests
    trigger: pull_request
    # Suffix for job name
    identifier: "kraft-components"
    targets:
      # This target is not used at all by our tests, but it has to be one of the available - https://packit.dev/docs/configuration/#aliases
      - fedora-38-x86_64
      - fedora-38-aarch64
    # We don't need to build any packages for Fedora/RHEL/CentOS, it is not related to Strimzi tests
    skip_build: true
    tf_extra_params:
      test:
        fmf:
          name: kraft-components
      settings:
        pipeline:
          timeout: 8h